#!/usr/bin/env python3
"""Render the human-readable resource catalogue from library/resources.json.

`library/resources.json` is the researched, licence-verified catalogue of free Godot
resources: what exists, what it is licensed under, and what problem it solves. It is
*not* a list of things vendored into this repository — most entries are still upstream.
`THIRD_PARTY_LICENSES.md` remains the record of what we have actually copied in.

This renders it grouped by the need a resource serves, because that is how someone
arrives at it ("I need object pooling"), not by upstream project name.

    python3 tools/build_resources_doc.py
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "library" / "resources.json"
OUT = REPO / "docs" / "RESOURCES.md"

# Licence strings the researchers flagged as unusable, in whole or in part. Matching is
# substring-based and deliberately broad: a false positive costs a footnote, a false
# negative costs a licence violation.
FORBIDDEN_MARKERS = ("GPL", "CC-BY-NC", "CC-BY-SA", "BY-NC", "BY-SA", "-ND", "FORBIDDEN", "COPYLEFT")

SECTION_ORDER = [
    ("genre-kit", "Genre kits and templates"),
    ("complete-game", "Complete open-source games to study"),
    ("framework", "Frameworks"),
    ("addon", "Addons and subsystems"),
    ("tool", "Tooling, testing and CI"),
    ("github-action", "CI actions"),
    ("shader-pack", "Shader collections"),
    ("single-shader", "Individual shaders"),
    ("art-asset", "Art assets"),
    ("model-pack", "3D model packs"),
    ("font", "Fonts"),
    ("audio-asset", "Audio"),
    ("reference", "Reference and learning material"),
]


def is_forbidden(entry: dict) -> bool:
    blob = f"{entry.get('license', '')} {entry.get('asset_license_note', '')}".upper()
    return any(marker in blob for marker in FORBIDDEN_MARKERS)


def main() -> int:
    if not CATALOG.is_file():
        print(f"error: {CATALOG.relative_to(REPO)} missing", file=sys.stderr)
        return 1

    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    entries = data.get("resources", [])
    unreachable = data.get("unreachable", [])

    usable = [e for e in entries if not is_forbidden(e)]
    flagged = [e for e in entries if is_forbidden(e)]
    by_kind: dict[str, list[dict]] = defaultdict(list)
    for entry in usable:
        by_kind[entry.get("kind", "other")].append(entry)

    lines = [
        "# Free Godot resources — researched and licence-verified",
        "",
        "Generated by `tools/build_resources_doc.py` from `library/resources.json`.",
        "Do not edit by hand.",
        "",
        f"**{len(entries)} resources**, each with its licence checked by fetching the actual "
        "licence file rather than trusting a README badge. "
        f"{len(flagged)} are flagged as unusable and listed at the end with the reason.",
        "",
        "> **These are not vendored.** This is a catalogue of what exists and what it is "
        "licensed under — a shortlist to pull from when a need comes up. What has actually "
        "been copied into this repository is recorded in `../THIRD_PARTY_LICENSES.md`.",
        "",
        "## Licensing rules",
        "",
        "- **Allowed code**: MIT, Apache-2.0, BSD, ISC, zlib, Unlicense, CC0, MPL-2.0 (flag it).",
        "- **Allowed assets**: CC0, OFL (fonts), CC-BY (with attribution recorded).",
        "- **Forbidden**: GPL/LGPL/AGPL, CC-BY-SA, CC-BY-NC, CC-BY-ND, non-commercial terms,",
        "  and any repository with no licence file at all.",
        "- Code and assets are licensed **separately** — an MIT repository can ship non-free art.",
        "  Several entries below are exactly that trap; they are flagged.",
        "",
    ]

    for kind, title in SECTION_ORDER:
        items = by_kind.pop(kind, [])
        if not items:
            continue
        items.sort(key=lambda e: (-(e.get("relevance") or 0), e.get("name", "").lower()))
        lines += [f"## {title}", "", "| Resource | Licence | Godot | What it gives you |", "| --- | --- | --- | --- |"]
        for entry in items:
            name = entry.get("name", "?")
            url = entry.get("url", "")
            link = f"[{name}]({url})" if url else name
            gd = (entry.get("godot_version") or "").split("(")[0].strip()[:14] or "—"
            why = " ".join(str(entry.get("teaches") or entry.get("why") or "").split())
            if len(why) > 190:
                why = why[:189].rsplit(" ", 1)[0] + "…"
            lines.append(f"| {link} | {entry.get('license', '?')} | {gd} | {why} |")
        lines.append("")

    for kind, items in sorted(by_kind.items()):
        lines += [f"## {kind}", "", "| Resource | Licence | What it gives you |", "| --- | --- | --- |"]
        for entry in sorted(items, key=lambda e: -(e.get("relevance") or 0)):
            link = f"[{entry.get('name','?')}]({entry.get('url','')})"
            why = " ".join(str(entry.get("teaches") or entry.get("why") or "").split())[:190]
            lines.append(f"| {link} | {entry.get('license', '?')} | {why} |")
        lines.append("")

    if flagged:
        lines += [
            "## Flagged — do not import",
            "",
            "Found during research and rejected on licence grounds. Recorded so nobody "
            "re-discovers them and imports them by mistake. Several are MIT code with "
            "non-free art, which is the trap worth remembering.",
            "",
            "| Resource | Licence problem |",
            "| --- | --- |",
        ]
        for entry in sorted(flagged, key=lambda e: e.get("name", "")):
            note = entry.get("asset_license_note") or ""
            problem = " ".join(f"{entry.get('license','?')} {note}".split())[:180]
            lines.append(f"| [{entry.get('name','?')}]({entry.get('url','')}) | {problem} |")
        lines.append("")

    if unreachable:
        lines += [
            "## Known but unreachable from this environment",
            "",
            "The network policy in our containers blocks these hosts (codeberg.org, itch.io, "
            "OpenGameArt, Freesound, kenney.nl, godotshaders.com and similar), so they cannot "
            "be fetched here. They are still worth knowing about — fetch them from a normal "
            "machine and vendor them through the usual licence check.",
            "",
        ]
        for item in sorted({" ".join(str(u).split()) for u in unreachable}):
            lines.append(f"- {item[:300]}")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)}: {len(usable)} usable, {len(flagged)} flagged, "
          f"{len(unreachable)} unreachable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
